using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Fallout.Common.Execution;
using Fallout.Common.IO;
using Fallout.Common.Utilities;
using static Fallout.Common.CI.BuildServerConfigurationGeneration;

namespace Fallout.Common.CI;

[AttributeUsage(AttributeTargets.Class)]
public abstract class ConfigurationAttributeBase : Attribute, IConfigurationGenerator
{
    public IFalloutBuild Build { get; internal set; }

    public string DisplayName => HostType.Name + (string.IsNullOrEmpty(IdPostfix) ? string.Empty : $" ({IdPostfix})");
    public string HostName => HostType.Name;
    public string Id => HostName + (string.IsNullOrEmpty(IdPostfix) ? string.Empty : $"_{IdPostfix}");
    public virtual string IdPostfix => string.Empty;

    public bool AutoGenerate { get; set; } = true;
    public abstract Type HostType { get; }
    public abstract AbsolutePath ConfigurationFile { get; }
    public abstract IEnumerable<AbsolutePath> GeneratedFiles { get; }

    public abstract IEnumerable<string> RelevantTargetNames { get; }
    public abstract IEnumerable<string> IrrelevantTargetNames { get; }

    public abstract CustomFileWriter CreateWriter(StreamWriter streamWriter);
    public abstract ConfigurationEntity GetConfiguration(IReadOnlyCollection<ExecutableTarget> relevantTargets);

    // Used by legacy CI providers (AzurePipelines, AppVeyor, TeamCity, SpaceAutomation) that still emit
    // ./build.cmd-style step invocations. GitHubActions doesn't read this since v11 — the generator now
    // emits a three-step setup-dotnet / tool restore / dotnet fallout shape. Falls back to "build.cmd"
    // when no file is found so generators don't throw mid-emit; consumers who removed build.cmd will see
    // the broken reference at runtime instead.
    protected virtual string BuildCmdPath =>
        Build.RootDirectory.GlobFiles("build.cmd", "*/build.cmd")
            .Select(x => Build.RootDirectory.GetUnixRelativePathTo(x).ToString())
            .FirstOrDefault() ?? "build.cmd";

    public void Generate(IReadOnlyCollection<ExecutableTarget> executableTargets)
    {
        var relevantTargets = RelevantTargetNames
            .SelectMany(x => ExecutionPlanner.GetExecutionPlan(executableTargets, new[] { x }))
            .Distinct()
            .Where(x => !IrrelevantTargetNames.Contains(x.Name)).ToList();
        var configuration = GetConfiguration(relevantTargets);

        using var stream = CreateStream();
        var writer = CreateWriter(stream);
        writer.WriteComment("------------------------------------------------------------------------------");
        writer.WriteComment("<auto-generated>");
        writer.WriteComment();
        writer.WriteComment("    This code was generated.");
        writer.WriteComment();
        writer.WriteComment("    - To turn off auto-generation set:");
        writer.WriteComment();
        writer.WriteComment($"        [{GetType().Name.TrimEnd(nameof(Attribute))} ({nameof(IConfigurationGenerator.AutoGenerate)} = false)]");
        writer.WriteComment();
        writer.WriteComment("    - To trigger manual generation invoke:");
        writer.WriteComment();
        writer.WriteComment($"        fallout --{ConfigurationParameterName} {Id} --host {HostName}");
        writer.WriteComment();
        writer.WriteComment("</auto-generated>");
        writer.WriteComment("------------------------------------------------------------------------------");
        writer.WriteLine();
        writer.Write(configuration.Write);
    }

    protected virtual StreamWriter CreateStream()
    {
        return new StreamWriter(File.Open(ConfigurationFile, FileMode.Create));
    }

    public virtual void SerializeState()
    {
    }
}
