name: 💡 Feature Idea
description: "Suggest new features for the project."
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        _Hi there :wave: and thanks for taking the time to send a feature idea!_
        
        _Before you continue, please check the [contribution guidelines](https://github.com/Fallout-build/Fallout/blob/main/CONTRIBUTING.md)._

  - type: textarea
    attributes:
      label: Description
      description: What should the new feature do?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Usage Example
      description: How would the proposed feature be used?

  - type: textarea
    attributes:
      label: Alternative
      description: What is the current alternative?

  - type: dropdown
    id: pull-request
    attributes:
      label: Could you help with a pull-request?
      description: See the [contribution guidelines](https://github.com/Fallout-build/Fallout/blob/main/CONTRIBUTING.md).
      options:
        - "No"
        - "Yes"
    validations:
      required: true
