//HintName: Solution.g.cs
// <auto-generated/>

using Microsoft.VisualStudio.SolutionPersistence.Model;
using Fallout.Common.ProjectModel;
using Fallout.Common.IO;
using System.Runtime.CompilerServices;

internal class Solution(SolutionModel model, AbsolutePath path) : Fallout.Common.ProjectModel.Solution(model, path)
{
    public Fallout.Common.ProjectModel.Project _build => this.GetProject("_build");
    public Fallout.Common.ProjectModel.Project Fallout_Build => this.GetProject("Fallout.Build");
    public Fallout.Common.ProjectModel.Project Fallout_Build_Shared => this.GetProject("Fallout.Build.Shared");
    public Fallout.Common.ProjectModel.Project Fallout_Build_Tests => this.GetProject("Fallout.Build.Tests");
    public Fallout.Common.ProjectModel.Project Fallout_Common => this.GetProject("Fallout.Common");
    public Fallout.Common.ProjectModel.Project Fallout_Common_Tests => this.GetProject("Fallout.Common.Tests");
    public Fallout.Common.ProjectModel.Project Fallout_Components => this.GetProject("Fallout.Components");
    public Fallout.Common.ProjectModel.Project Fallout_GlobalTool => this.GetProject("Fallout.GlobalTool");
    public Fallout.Common.ProjectModel.Project Fallout_GlobalTool_Tests => this.GetProject("Fallout.GlobalTool.Tests");
    public Fallout.Common.ProjectModel.Project Fallout_Migrate => this.GetProject("Fallout.Migrate");
    public Fallout.Common.ProjectModel.Project Fallout_Migrate_Analyzers => this.GetProject("Fallout.Migrate.Analyzers");
    public Fallout.Common.ProjectModel.Project Fallout_Migrate_Analyzers_Tests => this.GetProject("Fallout.Migrate.Analyzers.Tests");
    public Fallout.Common.ProjectModel.Project Fallout_Migrate_Tests => this.GetProject("Fallout.Migrate.Tests");
    public Fallout.Common.ProjectModel.Project Fallout_MSBuildTasks => this.GetProject("Fallout.MSBuildTasks");
    public Fallout.Common.ProjectModel.Project Fallout_ProjectModel => this.GetProject("Fallout.ProjectModel");
    public Fallout.Common.ProjectModel.Project Fallout_ProjectModel_Tests => this.GetProject("Fallout.ProjectModel.Tests");
    public Fallout.Common.ProjectModel.Project Fallout_SolutionModel => this.GetProject("Fallout.SolutionModel");
    public Fallout.Common.ProjectModel.Project Fallout_SolutionModel_Tests => this.GetProject("Fallout.SolutionModel.Tests");
    public Fallout.Common.ProjectModel.Project Fallout_SourceGenerators => this.GetProject("Fallout.SourceGenerators");
    public Fallout.Common.ProjectModel.Project Fallout_SourceGenerators_Tests => this.GetProject("Fallout.SourceGenerators.Tests");
    public Fallout.Common.ProjectModel.Project Fallout_Tooling => this.GetProject("Fallout.Tooling");
    public Fallout.Common.ProjectModel.Project Fallout_Tooling_Generator => this.GetProject("Fallout.Tooling.Generator");
    public Fallout.Common.ProjectModel.Project Fallout_Tooling_Tests => this.GetProject("Fallout.Tooling.Tests");
    public Fallout.Common.ProjectModel.Project Fallout_Utilities => this.GetProject("Fallout.Utilities");
    public Fallout.Common.ProjectModel.Project Fallout_Utilities_IO_Compression => this.GetProject("Fallout.Utilities.IO.Compression");
    public Fallout.Common.ProjectModel.Project Fallout_Utilities_IO_Globbing => this.GetProject("Fallout.Utilities.IO.Globbing");
    public Fallout.Common.ProjectModel.Project Fallout_Utilities_Net => this.GetProject("Fallout.Utilities.Net");
    public Fallout.Common.ProjectModel.Project Fallout_Utilities_Tests => this.GetProject("Fallout.Utilities.Tests");
    public Fallout.Common.ProjectModel.Project Fallout_Utilities_Text_Json => this.GetProject("Fallout.Utilities.Text.Json");
    public Fallout.Common.ProjectModel.Project Fallout_Utilities_Text_Yaml => this.GetProject("Fallout.Utilities.Text.Yaml");
    public Fallout.Common.ProjectModel.Project Fallout_VisualStudio_SolutionPersistence => this.GetProject("Fallout.VisualStudio.SolutionPersistence");
    public Fallout.Common.ProjectModel.Project Nuke_Build => this.GetProject("Nuke.Build");
    public Fallout.Common.ProjectModel.Project Nuke_Common => this.GetProject("Nuke.Common");
    public Fallout.Common.ProjectModel.Project Nuke_Common_Shim_Tests => this.GetProject("Nuke.Common.Shim.Tests");
    public Fallout.Common.ProjectModel.Project Nuke_Components => this.GetProject("Nuke.Components");

    public _misc misc => Unsafe.As<_misc>(this.GetSolutionFolder("misc"));

    internal class _misc(SolutionFolderModel model, Fallout.Common.ProjectModel.Solution solution) : Fallout.Common.ProjectModel.SolutionFolder(model, solution)
    {
    
    
    }
}