using System;
using System.Collections.Generic;
using System.Linq;
using Fallout.Common;
using Fallout.Common.IO;
using Fallout.Common.Utilities;
using Fallout.Utilities.Text.Yaml;
using static Fallout.Common.Constants;

namespace Fallout.Cli;

partial class Program
{
    private const string CommandName = "fallout";

    public static int Complete(string[] args, AbsolutePath rootDirectory, AbsolutePath buildScript)
    {
        if (rootDirectory == null)
            return 0;

        var words = args.Single();
        if (!words.StartsWithOrdinalIgnoreCase(CommandName))
            return 0;

        words = words[CommandName.Length..].TrimStart();

        var buildSchemaFile = GetBuildSchemaFile(rootDirectory);
        var completionFile = GetCompletionFile(rootDirectory);
        if (!buildSchemaFile.Exists() && !completionFile.Exists())
        {
            // Schema gets generated by HandleShellCompletionAttribute on any normal build run, so the
            // first time TAB fires before any build has happened we just return "no completions"; the
            // user's next `fallout <target>` invocation populates the schema and TAB works thereafter.
            return 1;
        }

        var position = EnvironmentInfo.GetNamedArgument<int?>("position");
        var completionItems = IsLegacy(rootDirectory)
            ? completionFile.ReadYaml<Dictionary<string, string[]>>()
            : CompletionUtility.GetItemsFromSchema(buildSchemaFile, GetProfileNames(rootDirectory));
        foreach (var item in CompletionUtility.GetRelevantItems(words, completionItems))
            Console.WriteLine(item);

        return 0;
    }
}
