using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Fallout.Common;
using Fallout.Common.IO;
using Fallout.Solutions;
using Fallout.Common.Utilities;
using Fallout.Common.Utilities.Collections;
using Scriban;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Fallout.SourceGenerators;

[Generator]
public class StronglyTypedSolutionGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        try
        {
            var allTypes = context.Compilation.Assembly.GlobalNamespace.GetAllTypes();
            var members = allTypes.SelectMany(x => x.GetMembers())
                .Where(x => x is IPropertySymbol or IFieldSymbol)
                .Select(x => (Member: x, AttributeData: x.GetAttributeData("global::Fallout.Solutions.SolutionAttribute")))
                .Where(x => x.AttributeData?.NamedArguments.SingleOrDefault(x => x.Key == "GenerateProjects").Value.Value as bool? ?? false)
                .ToList();
            if (members.Count == 0)
                return;

            var rootDirectory = GetRootDirectoryFrom(context.Compilation);

            foreach (var (member, attribute) in members)
            {
                var solutionFile = attribute.ConstructorArguments.FirstOrDefault().Value is string { Length: > 0 } relativeSlnPath
                    ? rootDirectory / relativeSlnPath
                    : GetSolutionFileFromParametersFile(rootDirectory, member.Name);
                var fancyNaming = attribute.NamedArguments.SingleOrDefault(x => x.Key == "FancyNames").Value.Value as bool? ?? false;

                var solution = solutionFile.ReadSolution();
                var hintName = member.Name + ".g.cs";
                var declaration = GetDeclaration(solution);

                // lang=csharp
                context.AddSource(hintName, $"""
                    // <auto-generated/>

                    using Fallout.Persistence.Solution.Model;
                    using Fallout.Solutions;
                    using Fallout.Common.IO;
                    using System.Runtime.CompilerServices;

                    {declaration}
                    """);

                continue;

                string GetDeclaration(IProjectContainer container, string folderName = null)
                {
                    var prefix = new string('_', container.Descendants(x => x.Parent).Count() + 1);
                    var model = new
                    {
                        IsSolution = container is Solution,
                        SolutionReference = container is Solution ? "this" : "solution",
                        Name = GetEscapedName(container switch
                        {
                            Solution => member.Name,
                            SolutionFolder folder => folderName ?? folder.Name,
                            _ => throw new ArgumentOutOfRangeException(nameof(container), container, null)
                        }),
                        Projects = container.Projects.OrderBy(x => x.Name).Select(x => new
                        {
                            x.Name,
                            EscapedName = GetEscapedName(x.Name),
                        }),
                        Folders = container.SolutionFolders.OrderBy(x => x.Name).Select(x => new
                        {
                            x.Name,
                            TypeName = $"{prefix}{GetEscapedName(x.Name)}",
                            EscapedName = GetEscapedName(x.Name),
                        }),
                        Declarations = container.SolutionFolders.OrderBy(x => x.Name)
                            .Select(x => GetDeclaration(x, $"{prefix}{GetEscapedName(x.Name)}")).ToArray(),
                    };

                    // lang=csharp
                    var template = Template.Parse("""
                        {{~ if is_solution ~}}
                        internal class {{ name }}(SolutionModel model, AbsolutePath path) : Fallout.Solutions.Solution(model, path)
                        {{~ else ~}}
                        internal class {{ name }}(SolutionFolderModel model, Fallout.Solutions.Solution solution) : Fallout.Solutions.SolutionFolder(model, solution)
                        {{~ end ~}}
                        {
                        {{~ for project in projects ~}}
                            public Fallout.Solutions.Project {{ project.escaped_name }} => this.GetProject("{{ project.name }}");
                        {{~ end ~}}

                        {{~ for folder in folders ~}}
                            public {{ folder.type_name }} {{ folder.escaped_name }} => Unsafe.As<{{ folder.type_name }}>(this.GetSolutionFolder("{{ folder.name }}"));
                        {{~ end ~}}

                        {{~ for declaration in declarations ~}}
                            {{ declaration }}
                        {{~ end ~}}
                        }
                        """);
                    return template.Render(model);

                    // C# identifiers can't start with a digit and can only contain
                    // letters/digits/underscore. The old regex `(^[\W^\d]|[\W])` was
                    // attempting both but the `^\d` inside the character class was
                    // misread as "match `^` or `\d`" rather than "starts with digit".
                    // Folders like `00-Build` produced invalid output. Upstream fix
                    // from nuke-build/nuke#1581.
                    string GetEscapedName(string name)
                    {
                        name = name
                            // .Replace(".", fancyNaming ? "丨" : "_")
                            .Replace(".", fancyNaming ? "٠" : "_")
                            .ReplaceRegex(@"[^A-Za-z0-9_]", _ => "_");

                        if (Regex.IsMatch(name, @"^[0-9]"))
                            return "_" + name;

                        return name;
                    }
                }
            }
        }
        catch (Exception exception)
        {
            var diagnostic = Diagnostic.Create(
                "NUKE001",
                nameof(StronglyTypedSolutionGenerator),
                exception.Message,
                DiagnosticSeverity.Error,
                DiagnosticSeverity.Error,
                isEnabledByDefault: true,
                warningLevel: 0);
            context.ReportDiagnostic(diagnostic);
        }

        return;

        static AbsolutePath GetSolutionFileFromParametersFile(AbsolutePath rootDirectory, string memberName)
        {
            var parametersFile = Constants.GetDefaultParametersFile(rootDirectory);
            Assert.FileExists(parametersFile);
            var obj = JsonNode.Parse(File.ReadAllText(parametersFile)).NotNull().AsObject();
            var solutionRelativePath = obj[memberName].NotNull($"Property '{memberName}' does not exist in '{parametersFile}'.").GetValue<string>();
            return rootDirectory / solutionRelativePath.NotNull();
        }

        static AbsolutePath GetRootDirectoryFrom(Compilation compilation)
        {
            var syntaxPath = compilation.SyntaxTrees.First().FilePath;
            var startDirectory = Path.GetDirectoryName(File.Exists(syntaxPath)
                ? syntaxPath
                // For testing only
                : Directory.GetCurrentDirectory());
            return Constants.TryGetRootDirectoryFrom(startDirectory).NotNull();
        }
    }
}
